# Automated deployment to Ubuntu server for Skynet Frontend
name: Deploy Frontend to Ubuntu

on:
  push:
    branches: [main]
  workflow_dispatch: # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to Ubuntu Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # Navigate to project directory
            cd /var/www/skynet/skynet-india-revamp
            
            # Pull latest changes
            git pull origin main
            
            # Install dependencies if package.json changed
            if git diff HEAD^ HEAD --name-only | grep -q "package.json"; then
              echo "📦 Installing dependencies..."
              npm install
            fi
            
            # Build the application
            echo "🔨 Building application..."
            npm run build
            
            # Restart PM2 process
            echo "🔄 Restarting application..."
            pm2 restart frontend
            
            # Save PM2 state
            pm2 save
            
            echo "✅ Frontend deployment complete!"
            
      - name: Verify Deployment
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # Check if frontend is running
            pm2 status frontend
            
            # Check application health
            curl -I http://localhost:3000 || echo "Health check failed"